import { getSession } from "@/actions/auth-actions";
import { QUERY_KEY } from "@/constants/query.const";
import { cn } from "@/lib/utils";
import Providers from "@/providers/providers";
import { prefetchQuery } from "@/utils/server-query";
import { HydrationBoundary } from "@tanstack/react-query";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { TOKEN_CONFIG } from "@/constants/token.const";
import { cookies } from "next/headers";
import "./globals.css";

const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const hasSession = cookieStore.has(TOKEN_CONFIG.SESSION_TOKEN_NAME);

  let dehydratedState = null;

  if (hasSession) {
    const queryData = await prefetchQuery([QUERY_KEY.SESSION], getSession);
    dehydratedState = queryData.dehydratedState;
  }

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", publicSans.variable)}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <HydrationBoundary state={dehydratedState}>
            {children}
          </HydrationBoundary>
        </Providers>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
